src/java/com/supinfo/supforum/controller/ForumController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.supinfo.supforum.controller;

import com.supinfo.supforum.service.ForumService;
import com.supinfo.supforum.service.MessageService;
import com.supinfo.supforum.service.UserService;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author Mathieu
 */
@ManagedBean
@SessionScoped
public class ForumController {
    
    @EJB
    UserService userService;
    
    @EJB
    MessageService messageService;
    
    @EJB
    ForumService forumService;
    
    @ManagedProperty(value = "#{navigationBean}")
    private NavigationBean navigationBean;
    
    public NavigationBean getNavigationBean(){
        return this.navigationBean;
    }
    
    public void setNavigationBean(NavigationBean navigationBean) {
        this.navigationBean = navigationBean;
    }
    
    
    public ForumController(){
        
    }
    
    public String getForumCreadted(){
        
        return forumService.getCreatedDate().toString();
    }
    
    public int getNbUsers(){
        return userService.getNbUsers();
    }
    
    public int getNbMessages(){
        return messageService.getNbMessages();
    }
}

src/java/com/supinfo/supforum/controller/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.supinfo.supforum.controller;

import com.supinfo.supforum.entity.User;
import static com.supinfo.supforum.filter.AuthFilter.SESSION_USER;
import com.supinfo.supforum.service.UserService;
import com.supinfo.supforum.util.SessionUtil;
import java.io.IOException;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.event.PhaseEvent;
import javax.servlet.http.HttpSession;

/**
 *
 * @author Mathieu
 */
@ManagedBean
@SessionScoped
public class LoginController {
    
    @EJB
    UserService userService;
    
    @ManagedProperty(value = "#{navigationBean}")
    private NavigationBean navigationBean;
    
    private User user = new User();
    
    
    public LoginController() {
    }
    
    public void checkUser() throws IOException{
        
        HttpSession session = SessionUtil.getSession();
        if(session.getAttribute(SESSION_USER) != null){
            System.out.println("test");
            ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
            ec.redirect(ec.getRequestContextPath() + "/auth/forum.xhtml");
        }
    }
    
    public String login(){
        
        HttpSession session = SessionUtil.getSession();
        String forward = "";
        
        try {
            user = userService.userExists(user.getUsername(), user.getPassword());
            
            if(user != null){
                
                session.setAttribute(SESSION_USER, user);
                forward = navigationBean.redirectToAuthForum();
            }else{

            }
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage(
                    null,
                    new FacesMessage(FacesMessage.SEVERITY_WARN,
                    "Invalid Login!",
                    "Please Try Again!"));
            forward = navigationBean.toLogin(); 
        }
        
        return forward;
    }
    
    
    public User getUser(){
        return this.user;
    }
    
    public NavigationBean getNavigationBean(){
        return this.navigationBean;
    }
    
    public void setNavigationBean(NavigationBean navigationBean) {
        this.navigationBean = navigationBean;
    }
    
}

src/java/com/supinfo/supforum/controller/RegisterController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.supinfo.supforum.controller;

import com.supinfo.supforum.entity.User;
import static com.supinfo.supforum.filter.AuthFilter.SESSION_USER;
import com.supinfo.supforum.service.UserService;
import com.supinfo.supforum.util.SessionUtil;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

/**
 *
 * @author Mathieu
 */
@ManagedBean
@SessionScoped
public class RegisterController {
    
    @EJB
    UserService userService;
    
    @ManagedProperty(value = "#{navigationBean}")
    private NavigationBean navigationBean;
    
    private User user = new User();
    
    public RegisterController(){
        
    }
    
    public void checkUser() throws IOException{
        
        HttpSession session = SessionUtil.getSession();
        if(session.getAttribute(SESSION_USER) != null){
            System.out.println("test");
            ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
            ec.redirect(ec.getRequestContextPath() + "/auth/forum.xhtml");
        }
    }
    
    public String register(){
        
        
        User u = new User(user.getUsername(), user.getPassword(), user.getEmail());
        
        try {
            userService.addUser(u);
            navigationBean.redirectToAuthForum();
        } catch (Exception ex) {
            Logger.getLogger(RegisterController.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return "";
    }
    
    public User getUser(){
        return user;
    }
    
    public NavigationBean getNavigationBean(){
        return this.navigationBean;
    }
    
    public void setNavigationBean(NavigationBean navigationBean) {
        this.navigationBean = navigationBean;
    }
}

web/footer.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet name="./css/default.css"/>
        <h:outputStylesheet name="./css/cssLayout.css"/>
        <title>Facelets Template</title>
    </h:head>

    <h:body>

        <ui:composition
            xmlns="http://www.w3.org/1999/xhtml"
            xmlns:f="http://java.sun.com/jsf/core"
            xmlns:h="http://java.sun.com/jsf/html"
            xmlns:ui="http://java.sun.com/jsf/facelets">

            <f:view>
                <h:outputText value="Created : #{forumController.forumCreadted}" /> |
                <h:outputText value=" users #{forumController.nbUsers}" /> |
                <h:outputText value=" messages #{forumController.nbMessages}" />
            </f:view>
                
        </ui:composition>

    </h:body>

</html>

web/forum.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet name="./css/default.css"/>
        <h:outputStylesheet name="./css/cssLayout.css"/>
        <title>SupForum</title>
    </h:head>

    <h:body>

        <div id="top">
            <ui:insert name="header">
                <ui:include src="header.xhtml" />
            </ui:insert>
        </div>

        <div id="content" class="center_content">
            <f:view>


                <h:form>
                    <h1><h:outputText value="Forum"/></h1>
                    <h:dataTable value="#{categoryController.categories}" var="category">
                        <h:column>
                            <ul>
                                <li><h:outputText value="#{category.name}"/></li>
                                
                                <h:form>
                                    <h:dataTable value="#{category.boards}" var="board">
                                        <h:column>
                                            <li>
                                                <ul>
                                                    <li><h:outputText value="#{board.name}"/></li>
                                                </ul>
                                            </li>
                                        </h:column>
                                    </h:dataTable>
                                </h:form>
                            </ul>
                        </h:column>
                    </h:dataTable>
                </h:form>
            </f:view>

        </div>

        <div id="bottom">
            <ui:insert name="statsForum">
                <ui:include src="footer.xhtml" />
            </ui:insert>
        </div>

    </h:body>

</html>

web/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet name="./css/default.css"/>
        <h:outputStylesheet name="./css/cssLayout.css"/>
        <title>Facelets Template</title>
    </h:head>

    <h:body>

        <ui:composition
            xmlns="http://www.w3.org/1999/xhtml"
            xmlns:f="http://java.sun.com/jsf/core"
            xmlns:h="http://java.sun.com/jsf/html"
            xmlns:ui="http://java.sun.com/jsf/facelets">

            <f:view>
                <h:link value="Forum" outcome="#{forumController.navigationBean.redirectToForum()}" />
                <h:link value="Log in" outcome="login"/>
                <h:link value="Register" outcome="register"/>
            </f:view>
                
        </ui:composition>

    </h:body>

</html>

web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet name="./css/default.css"/>
        <h:outputStylesheet name="./css/cssLayout.css"/>
        <title>Facelets Template</title>
        <f:event type="preRenderView" listener="#{loginController.checkUser}" />
    </h:head>

    <h:body>

        <div id="top">
            <ui:insert name="header">
                <ui:include src="header.xhtml" />
            </ui:insert>
        </div>

        <div id="content" class="center_content">
            <h:form>
                <p>
                    <h:panelGroup>
                        <h:outputLabel id="usernameLabel" for="username" value="Username : " />
                        <h:inputText id="username" value="#{loginController.user.username}" required="true" /><br />
                        
                        <h:outputLabel id="passwordLabel" for="password" value="Password : " />
                        <h:inputSecret id="password" value="#{loginController.user.password}" required="true" />
                        <h:commandButton action="#{loginController.login}" value="Submit" />
                    </h:panelGroup>
                </p>
            </h:form>
        </div>

        <div id="bottom">
            <ui:insert name="statsForum">
                <ui:include src="footer.xhtml" />
            </ui:insert>
        </div>

    </h:body>

</html>

web/register.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet name="./css/default.css"/>
        <h:outputStylesheet name="./css/cssLayout.css"/>
        <title>Supinfo</title>
        <f:event type="preRenderView" listener="#{loginController.checkUser}" />
    </h:head>

    <h:body>

        <div id="top">
            <ui:insert name="header">
                <ui:include src="header.xhtml" />
            </ui:insert>
        </div>

        <div id="content" class="center_content">
            <f:view>


                <h:form>
                    <h1><h:outputText value="Register"/></h1>
                    <h:panelGrid columns="2">
                        <h:outputLabel value="Username:" for="username" />
                        <h:inputText id="username" value="#{registerController.user.username}" title="Username" required="true" requiredMessage="The Username field is required."/>
                        <h:outputLabel value="Email:" for="email" />
                        <h:inputText id="email" value="#{registerController.user.email}" title="Email" required="true" requiredMessage="The Email field is required." validator="emailValidator"/>
                        <h:outputLabel value="Password:" for="password" />
                        <h:inputSecret id="password" value="#{registerController.user.password}" title="Password" required="true" requiredMessage="The Password field is required."/>                      
                        <h:commandButton action="#{registerController.register}" value="Submit" />
                    </h:panelGrid>
                </h:form>
            </f:view>

        </div>

        <div id="bottom">
            <ui:insert name="statsForum">
                <ui:include src="footer.xhtml" />
            </ui:insert>
        </div>

    </h:body>

</html>